CREATE TABLE dna
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dna       VARCHAR(255)                             NOT NULL,
    is_mutant BOOLEAN                                  NOT NULL,
    CONSTRAINT pk_dna PRIMARY KEY (id)
);
